/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gesturebasedshopping;


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class CameraFrame extends javax.swing.JFrame {
    public  int count=1;
    public static String pname="camera1";
    public static String pdname="<html><c>KODAK PIXPRO WPZ2</c></html>";
    public static String path="/camera1.jpg";
    public static String pdetails="<html><b>Price</b>: $149.00<br/><b>Model Number</b>: Kodak PIXPRO"
                 + "<br/><b>Screen Size</b>: 2.7 Inches<br/><b>Brand</b>: KODAK"
                 + "<br/><b>Optical Zoom</b>: 4 x</html>";
   
    /**
     * Creates new form StoreFrame
     */
    public CameraFrame() {
        initComponents();
         jLabel3.setHorizontalAlignment(JLabel.CENTER);
         jLabel3.setSize(300, 400);
         jButton2.setOpaque(false);       
         jLabel4.setText(pdname);
         jLabel3.setIcon(resizeIcon(path));
         jLabel5.setText(pdetails);
                 
         if(pname.equals("camera1"))
             jButton3.setVisible(false);
         if(pname.equals("camera4"))
             jButton1.setVisible(false);
                
         GestureInfo.frameno=4;
    }
     ImageIcon resizeIcon(String path)
    {
        ImageIcon icon=new ImageIcon (getClass().getResource(path));
        Image image = icon.getImage().getScaledInstance(416, 250, Image.SCALE_DEFAULT); // transform it 
        icon = new ImageIcon(image);
        return icon;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rightarrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("More Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leftarrow.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("MARINE ELECTRONICS ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Show these Gestures");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next.jpeg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Previous.jpeg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moreinfo.jpeg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(363, 363, 363))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(765, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

      public void mainFrame(){
          GestureInfo.ht.setCameraFrameObject(null);
          this.dispose();
         MainFrame lf = new MainFrame();
         GestureInfo.ht.setMainFrameObject(lf);
         lf.getContentPane().setBackground(Color.WHITE);
         lf.setVisible(true);
         lf.setExtendedState(MAXIMIZED_BOTH);
         
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        funPrevious();

    }//GEN-LAST:event_jButton3ActionPerformed

    public void funPrevious()
    {
         if(count==4)
        {
         jLabel4.setText("<html><c>Acuvar 16MP Megapixel</c></html>");
         jLabel3.setIcon(resizeIcon("/camera3.jpg"));
         String str="<html><b>Price</b>: $24.99<br/><b>Model Number</b>: Acuvar 16MP"
                 + "<br/><b>Screen Size</b>: 2.4 Inches<br/><b>Brand</b>: Acuvar"
                 + "<br/><b>Optical Zoom</b>: 0.01 x</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
         count--;
         
           
        }
        else if(count==3)
        {
         jLabel4.setText("<html><c>Sony RX100 VII Premium</c></html>");
         jLabel3.setIcon(resizeIcon("/camera2.jpg"));
         String str="<html><b>Price</b>: $1,298.00<br/><b>Model Number</b>: RX100 VII"
                 + "<br/><b>Screen Size</b>: 3.0 Inches<br/><b>Brand</b>: SONY"
                 + "<br/><b>Optical Zoom</b>: 8 x</html>";
         
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
          count--;
         
           
        }
        else if(count==2)
        {
         jLabel4.setText("<html><c>KODAK PIXPRO WPZ2</c></html>");
         jLabel3.setIcon(resizeIcon("/camera1.jpg"));
         String str="<html><b>Price</b>: $149.00<br/><b>Model Number</b>: Kodak PIXPRO"
                 + "<br/><b>Screen Size</b>: 2.7 Inches<br/><b>Brand</b>: KODAK"
                 + "<br/><b>Optical Zoom</b>: 4 x</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(false);
         count--;  
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        productDetails();

    }//GEN-LAST:event_jButton2ActionPerformed

     public void productDetails()
    { 
          if(count==1)
          {
           
            CameraDetailInfoFrame.path1="/camera1.jpg";
            CameraDetailInfoFrame.path2="/camera1_1.jpg";
            CameraDetailInfoFrame.path3="/camera1_2.jpg";
            CameraDetailInfoFrame.path4="/camera1_3.jpg";
            CameraDetailInfoFrame.path5="/camera1_4.jpg";
            CameraDetailInfoFrame.pdname="<html><c>KODAK PIXPRO WPZ2</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Connectivity Technology: USB Micro-B (USB 2.0)"
                    + "<br/>Flash Memory Type: Single Slot: microSD/microSDHC"
                 + "<br/>Photo Sensor Technology: CMOS"
                    + "<br/>Included Components: Camera Body & Lens"
                 + "<br/>Special Feature : Waterproof</html>";
            CameraDetailInfoFrame.pdetails=details;
            CameraDetailInfoFrame.pname="camera1";
            
            
          
          }
          else if(count==2)
          {
            pname=pname.trim();
            CameraDetailInfoFrame.path1="/camera2.jpg";
            CameraDetailInfoFrame.path2="/camera2_1.jpg";
            CameraDetailInfoFrame.path3="/camera2_2.jpg";
            CameraDetailInfoFrame.path4="/camera2_3.jpg";
            CameraDetailInfoFrame.path5="/camera2_4.jpg";
            CameraDetailInfoFrame.pdname="<html><c>Sony RX100 VII</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Connectivity Technology: 3.5mm Microphone, HDMI D (Micro), USB Micro-B (USB 2.0)"
                    + "<br/>Effective Still Resolution: 20.1 MP"
                 + "<br/>Photo Sensor Size: 1-inch"
                    + "<br/>Included Components: Camera Body & Lens"
                 + "<br/>Special Feature : BIONZ X Image Processor and Front-End LSI; Built-In Flash</html>";
            CameraDetailInfoFrame.pdetails=details;
            CameraDetailInfoFrame.pname="camera2";
          
          }
           else if(count==3)
          {
            pname=pname.trim();
            CameraDetailInfoFrame.path1="/camera3.jpg";
            CameraDetailInfoFrame.path2="/camera3_1.jpg";
            CameraDetailInfoFrame.path3="/camera3_2.jpg";
            CameraDetailInfoFrame.path4="/camera3_3.jpg";
            CameraDetailInfoFrame.path5="/camera3_4.jpg";
            CameraDetailInfoFrame.pdname="<html><c>Acuvar 16MP Megapixel</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Connectivity Technology: USB"
                    + "<br/>Flash Memory Type: SD Card, SDHC"
                 + "<br/>Effective Still Resolution: 14 MP"
                    + "<br/>Included Components: Camera Body & Lens"
                 + "<br/>Special Feature : Image Stabilization</html>";
            CameraDetailInfoFrame.pdetails=details;
            CameraDetailInfoFrame.pname="camera3";
          
          }
          else if(count==4)
          {
            pname=pname.trim();
            CameraDetailInfoFrame.path1="/camera4.jpg";
            CameraDetailInfoFrame.path2="/camera4_1.jpg";
            CameraDetailInfoFrame.path3="/camera4_2.jpg";
            CameraDetailInfoFrame.path4="/camera4_3.jpg";
            CameraDetailInfoFrame.path5="/camera4_4.jpg";
            CameraDetailInfoFrame.pdname="<html><c>Minolta Pro Shot 16 Mega Pixel HD</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Connectivity Technology: HDMI, WiFi"
                    + "<br/>Effective Still Resolution: 16"
                 + "<br/>Photo Sensor Size: 1.23 inch"
                    + "<br/>Included Components: Camera Body & Lens"
                 + "<br/>Special Feature : Image Stabilization</html>";
            CameraDetailInfoFrame.pdetails=details;
            CameraDetailInfoFrame.pname="camera4";
          
          }
          GestureInfo.ht.setCameraFrameObject(null);
            this.dispose();
            CameraDetailInfoFrame tf = new CameraDetailInfoFrame();
            GestureInfo.ht.setCameraDetailInfoFrameObject(tf);
            tf.setVisible(true);
            tf.setExtendedState(MAXIMIZED_BOTH);
            tf.getContentPane().setBackground(Color.WHITE);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        funNext();

    }//GEN-LAST:event_jButton1ActionPerformed
 public void funNext()
    {
        if(count==1)
        {
                    
         jLabel4.setText("<html><c>Sony RX100 VII Premium</c></html>");
         jLabel3.setIcon(resizeIcon("/camera2.jpg"));
         String str="<html><b>Price</b>: $1,298.00<br/><b>Model Number</b>: RX100 VII"
                 + "<br/><b>Screen Size</b>: 3.0 Inches<br/><b>Brand</b>: SONY"
                 + "<br/><b>Optical Zoom</b>: 8 x</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
               
        }   
        
         else if(count==2)
        {
                    
         jLabel4.setText("<html><c>Acuvar 16MP Megapixel</c></html>");
         jLabel3.setIcon(resizeIcon("/camera3.jpg"));
         String str="<html><b>Price</b>: $24.99<br/><b>Model Number</b>: Acuvar 16MP"
                 + "<br/><b>Screen Size</b>: 2.4 Inches<br/><b>Brand</b>: Acuvar"
                 + "<br/><b>Optical Zoom</b>: 0.01 x</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
                 
        } 
        else if(count==3)
        {
                    
         jLabel4.setText("<html><c>Minolta Pro Shot 16 Mega Pixel HD</c></html>");
         jLabel3.setIcon(resizeIcon("/camera4.jpg"));
         String str="<html><b>Price</b>: $269.00<br/><b>Model Number</b>: MN53Z"
                 + "<br/><b>Screen Size</b>: 3.0 Inches<br/><b>Brand</b>: Minolta"
                 + "<br/><b>Optical Zoom</b>: 53 x</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
         jButton1.setVisible(false);
                  
        } 
    }
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
