/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gesturebasedshopping;


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;


public class TelevisionFrame extends javax.swing.JFrame {
    public  int count=1;
    public static String pname="tv1";
    public static String pdname="<html><c>Samsung UHD 8 Series AU8000</c></html>";
    public static String path="/tv1.jpg";
    public static String pdetails="<html><b>Price</b>: $997.99<br/><b>Model Number</b>: LED UHD 8 Series"
                 + "<br/><b>Screen Size</b>: 75 Inches<br/><b>Brand</b>: SAMSUNG"
                 + "<br/><b>Product Dimensions</b>: 13.1\"D x 66\"W x 39.5\"H</html>";
   
    /**
     * Creates new form StoreFrame
     */
    public TelevisionFrame() {
        initComponents();
         jLabel3.setHorizontalAlignment(JLabel.CENTER);
         jLabel3.setSize(300, 400);
         jButton2.setOpaque(false);       
         jLabel4.setText(pdname);
         jLabel3.setIcon(resizeIcon(path));
         jLabel5.setText(pdetails);
                 
         if(pname.equals("tv1"))
             jButton3.setVisible(false);
         if(pname.equals("tv4"))
             jButton1.setVisible(false);
                   
         GestureInfo.frameno=2;
    }
     ImageIcon resizeIcon(String path)
    {
        ImageIcon icon=new ImageIcon (getClass().getResource(path));
        Image image = icon.getImage().getScaledInstance(416, 250, Image.SCALE_DEFAULT); // transform it 
        icon = new ImageIcon(image);
        return icon;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rightarrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("More Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leftarrow.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("MARINE ELECTRONICS ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Show these Gestures");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Previous.jpeg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next.jpeg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moreinfo.jpeg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(857, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    void mainFrame(){
        GestureInfo.ht.setTelevisionFrameObject(null);
        this.dispose();
         MainFrame lf = new MainFrame();
         GestureInfo.ht.setMainFrameObject(lf);
         lf.getContentPane().setBackground(Color.WHITE);
         lf.setVisible(true);
         lf.setExtendedState(MAXIMIZED_BOTH);
          
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        funPrevious();

    }//GEN-LAST:event_jButton3ActionPerformed

   public  void funPrevious()
    {
         if(count==4)
        {
         jLabel4.setText("<html><c>VIZIO 40-inch D-Series Full HD</c></html>");
         jLabel3.setIcon(resizeIcon("/tv3.jpg"));
         String str="<html><b>Price</b>: $178.00<br/><b>Model Number</b>: D40F-J09"
                 + "<br/><b>Screen Size</b>: 40 Inches<br/><b>Brand</b>: VIZIO"
                 + "<br/><b>Product Dimensions</b>: 8.81\"D x 35.55\"W x 22.81\"H</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
         count--;
         
           
        }
        else if(count==3)
        {
         jLabel4.setText("<html><c>Sony Bravia XR Full Array LED</c></html>");
         jLabel3.setIcon(resizeIcon("/tv2.jpg"));
         String str="<html><b>Price</b>: $1699.99<br/><b>Model Number</b>: Sony 75 Inch 4K Ultra HD TV X90K Series"
                 + "<br/><b>Screen Size</b>: 75 Inches<br/><b>Brand</b>: SONY"
                 + "<br/><b>Product Dimensions</b>: 15.75\"D x 66\"W x 39.13\"H</html>";
         
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
          count--;
         
           
        }
        else if(count==2)
        {
         jLabel4.setText("<html><c>Samsung UHD 8 Series AU8000</c></html>");
         jLabel3.setIcon(resizeIcon("/tv1.jpg"));
         String str="<html><b>Price</b>: $997.99<br/><b>Model Number</b>: LED UHD 8 Series"
                 + "<br/><b>Screen Size</b>: 75 Inches<br/><b>Brand</b>: SAMSUNG"
                 + "<br/><b>Product Dimensions</b>: 13.1\"D x 66\"W x 39.5\"H</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(false);
         count--;  
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        productDetails();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void productDetails()
    { 
          if(count==1)
          {
           
            TelevisionDetailInfoFrame.path1="/tv1.jpg";
            TelevisionDetailInfoFrame.path2="/tv1_1.jpg";
            TelevisionDetailInfoFrame.path3="/tv1_2.jpg";
            TelevisionDetailInfoFrame.path4="/tv1_3.jpg";
            TelevisionDetailInfoFrame.path5="/tv1_4.jpg";
            TelevisionDetailInfoFrame.pdname="<html><c>Samsung UHD 8 Series AU8000</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Resolution: 4K | Refresh Rate: 60 hertz"
                    + "<br/>Special Features: Dynamic Crystal Color; Crystal Processor 4K; Smart TV with Multiple Voice"
                 + "<br/>Warranty Information: 1 year warranty"
                    + "<br/>Display Technology: LED"
                 + "<br/>Included Components : User Manual, E - Manual, OneRemote TM2180E with batteries, Power Cable</html>";
            TelevisionDetailInfoFrame.pdetails=details;
            TelevisionDetailInfoFrame.pname="tv1";
            
            
          
          }
          else if(count==2)
          {
            pname=pname.trim();
            TelevisionDetailInfoFrame.path1="/tv2.jpg";
            TelevisionDetailInfoFrame.path2="/tv2_1.jpg";
            TelevisionDetailInfoFrame.path3="/tv2_2.jpg";
            TelevisionDetailInfoFrame.path4="/tv2_3.jpg";
            TelevisionDetailInfoFrame.path5="/tv2_4.jpg";
            TelevisionDetailInfoFrame.pdname="<html><c>Sony Bravia XR Full Array LED</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Resolution: 4K | Refresh Rate: 120 hertz"
                    + "<br/>Special Features: XR HDR Remaster; XR Contrast; 4K XR Super Resolution; XR 4K Upscaling; 4K XR Smoothing"
                 + "<br/>Warranty Information: 1 year warranty"
                    + "<br/>Display Technology: Full Array LED"
                 + "<br/>Included Components : Television</html>";
            TelevisionDetailInfoFrame.pdetails=details;
            TelevisionDetailInfoFrame.pname="tv2";
          
          }
           else if(count==3)
          {
            pname=pname.trim();
            TelevisionDetailInfoFrame.path1="/tv3.jpg";
            TelevisionDetailInfoFrame.path2="/tv3_1.jpg";
            TelevisionDetailInfoFrame.path3="/tv3_2.jpg";
            TelevisionDetailInfoFrame.path4="/tv3_3.jpg";
            TelevisionDetailInfoFrame.path5="/tv3_4.jpg";
            TelevisionDetailInfoFrame.pdname="<html><c>VIZIO 40-inch D-Series Full HD</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Resolution: 1080p | Refresh Rate: 60 hertz"
                    + "<br/>Special Features: DTS Virtual:X, Free Channels with WatchFree+"
                 + "<br/>Warranty Information: 1 year warranty"
                    + "<br/>Display Technology: LCD"
                 + "<br/>Included Components : Power Cable, Remote Control, Stand</html>";
            TelevisionDetailInfoFrame.pdetails=details;
            TelevisionDetailInfoFrame.pname="tv3";
          
          }
          else if(count==4)
          {
            pname=pname.trim();
            TelevisionDetailInfoFrame.path1="/tv4.jpg";
            TelevisionDetailInfoFrame.path2="/tv4_1.jpg";
            TelevisionDetailInfoFrame.path3="/tv4_2.jpg";
            TelevisionDetailInfoFrame.path4="/tv4_3.jpg";
            TelevisionDetailInfoFrame.path5="/tv4_4.jpg";
            TelevisionDetailInfoFrame.pdname="<html><c>ATYME 32-inch Class HD LED</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Resolution: 1366x768 | Refresh Rate: 60 hertz"
                    + "<br/>Special Features: ‎Energy Efficient"
                 + "<br/>Warranty Information: 1 year warranty"
                    + "<br/>Display Technology: LED"
                 + "<br/>Included Components : User Manual, Remote</html>";
            TelevisionDetailInfoFrame.pdetails=details;
            TelevisionDetailInfoFrame.pname="tv4";
          
          }
          GestureInfo.ht.setTelevisionFrameObject(null);
            this.dispose();
            TelevisionDetailInfoFrame tf = new TelevisionDetailInfoFrame();
            GestureInfo.ht.setTelevisionDetailInfoFrameObject(tf);
            tf.setVisible(true);
            tf.setExtendedState(MAXIMIZED_BOTH);
            tf.getContentPane().setBackground(Color.WHITE);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        funNext();

    }//GEN-LAST:event_jButton1ActionPerformed
  public void funNext()
    {
        if(count==1)
        {
                    
         jLabel4.setText("<html><c>Sony Bravia XR Full Array LED</c></html>");
         jLabel3.setIcon(resizeIcon("/tv2.jpg"));
         String str="<html><b>Price</b>: $1699.99<br/><b>Model Number</b>: Sony 75 Inch 4K Ultra HD TV X90K Series"
                 + "<br/><b>Screen Size</b>: 75 Inches<br/><b>Brand</b>: SONY"
                 + "<br/><b>Product Dimensions</b>: 15.75\"D x 66\"W x 39.13\"H</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
               
        }   
        
         else if(count==2)
        {
                    
         jLabel4.setText("<html><c>VIZIO 40-inch D-Series Full HD</c></html>");
         jLabel3.setIcon(resizeIcon("/tv3.jpg"));
         String str="<html><b>Price</b>: $178.00<br/><b>Model Number</b>: D40F-J09"
                 + "<br/><b>Screen Size</b>: 40 Inches<br/><b>Brand</b>: VIZIO"
                 + "<br/><b>Product Dimensions</b>: 8.81\"D x 35.55\"W x 22.81\"H</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
                 
        } 
        else if(count==3)
        {
                    
         jLabel4.setText("<html><c>ATYME 32-inch Class HD LED</c></html>");
         jLabel3.setIcon(resizeIcon("/tv4.jpg"));
         String str="<html><b>Price</b>: $109.99<br/><b>Model Number</b>: 320GM5HD"
                 + "<br/><b>Screen Size</b>: 32 Inches<br/><b>Brand</b>: ATYME"
                 + "<br/><b>Product Dimensions</b>: 28.7 x 7.9 x 19 inches</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
         jButton1.setVisible(false);
                  
        } 
    }
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelevisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelevisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelevisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelevisionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelevisionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
