/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gesturebasedshopping;


import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



public class CameraDetailInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form StoreFrame
     */
    
    public static String path1="";
    public static String path2="";
    public static String path3="";
    public static String path4="";
    public static String path5="";
    public static String pdetails="";
    public static String pname="";
    public static String pdname="";
    
    public CameraDetailInfoFrame() {
        initComponents();
     //   jLabel2.setLocation(400, 50);
         jLabel3.setHorizontalAlignment(JLabel.CENTER);
         jLabel3.setSize(300, 400);
          jLabel4.setText(pdname);
          jLabel5.setText(pdetails);
         jButton2.setOpaque(false);
              GestureInfo.frameno=8;
                      
            ImageIcon icon1=new ImageIcon (getClass().getResource(path1));
            Image image1 = icon1.getImage().getScaledInstance(465, 250, Image.SCALE_DEFAULT); // transform it 
            icon1 = new ImageIcon(image1);
           
            
            jLabel3.setIcon(icon1);
            jLabel6.setIcon(resizeIcon(path2));
            jLabel7.setIcon(resizeIcon(path3));
            jLabel8.setIcon(resizeIcon(path4));
            jLabel9.setIcon(resizeIcon(path5));
           
           
      
    }
     ImageIcon resizeIcon(String path)
    {
        ImageIcon icon=new ImageIcon (getClass().getResource(path));
        Image image = icon.getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT); // transform it 
        icon = new ImageIcon(image);
        
        return icon;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Buy Now");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 100, 1050, 650);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("MARINE ELECTRONICS ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 990, 74);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buy.jpeg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1130, 470, 96, 133);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.jpeg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1250, 470, 96, 133);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Show these Gestures");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1160, 410, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           tokenGeneration();
                    
    }//GEN-LAST:event_jButton2ActionPerformed

    void tokenGeneration()
    {
         String item="";
        String price="";
        if(pname.equals("camera1"))
        {
            item="KODAK PIXPRO WPZ2";
            price="149.00";  
        }
        else if(pname.equals("camera2"))
        {
            item="Sony RX100 VII Premium";
            price="1,298.00";  
        }
        else  if(pname.equals("camera3"))
         {
              item="Acuvar 16MP Megapixel";
            price="24.99";
         }
        else  if(pname.equals("camera4"))
         {
              item="Minolta Pro Shot 16 Mega Pixel HD";
            price="269.00";
         }
    ArrayList temp=new ArrayList();
    temp.add(item);
    temp.add(price);
    GestureInfo.cart.add(temp);
         GestureInfo.ht.setCameraDetailInfoFrameObject(null);
            this.dispose();
            CartFrame pf = new CartFrame();
             GestureInfo.ht.setCartFrameObject(pf);
            pf.getContentPane().setBackground(Color.WHITE);
            pf.setVisible(true);
            pf.setExtendedState(MAXIMIZED_BOTH);
           
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       funBack();
           
    }//GEN-LAST:event_jButton3ActionPerformed

    void funBack()
    {
        int value=0;
        if(pname.equals("camera1"))
           {
               CameraFrame.pdname="<html><c>KODAK PIXPRO WPZ2</c></html>";
               CameraFrame.path="/camera1.jpg";
                      
               String str = "<html><b>Price</b>: $149.00<br/><b>Model Number</b>: Kodak PIXPRO"
                 + "<br/><b>Screen Size</b>: 2.7 Inches<br/><b>Brand</b>: KODAK"
                 + "<br/><b>Optical Zoom</b>: 4 x</html>";
               CameraFrame.pdetails=str;
               CameraFrame.pname = "camera1";
               CameraFrame.jButton1.setVisible(true);
               CameraFrame.jButton3.setVisible(false);
                             value=1;
           }
           else if(pname.equals("camera2"))
           {
                
               CameraFrame.pdname="<html><c>Sony RX100 VII Premium</c></html>";
               CameraFrame.path="/camera2.jpg";
               
               String str = "<html><b>Price</b>: $1,298.00<br/><b>Model Number</b>: RX100 VII"
                 + "<br/><b>Screen Size</b>: 3.0 Inches<br/><b>Brand</b>: SONY"
                 + "<br/><b>Optical Zoom</b>: 8 x</html>";

               CameraFrame.pdetails=str;
               CameraFrame.pname = "camera2";
               CameraFrame.jButton1.setVisible(true);
               CameraFrame.jButton3.setVisible(true);
                           
                      value=2;
           }
           else if(pname.equals("camera3"))
           {
              
               CameraFrame.pdname="<html><c>Acuvar 16MP Megapixel</c></html>";
               CameraFrame.path="/camera3.jpg";
               
               String str = "<html><b>Price</b>: $24.99<br/><b>Model Number</b>: Acuvar 16MP"
                 + "<br/><b>Screen Size</b>: 2.4 Inches<br/><b>Brand</b>: Acuvar"
                 + "<br/><b>Optical Zoom</b>: 0.01 x</html>";

               CameraFrame.pdetails=str;
               CameraFrame.pname = "camera3";
               CameraFrame.jButton1.setVisible(true);
               CameraFrame.jButton3.setVisible(true);
           
            value=3;
               
                      
           }
         else if(pname.equals("camera4"))
           {
               CameraFrame.pdname="<html><c>Minolta Pro Shot 16 Mega Pixel HD</c></html>";
               CameraFrame.path="/camera4.jpg";
               
               String str = "<html><b>Price</b>: $269.00<br/><b>Model Number</b>: MN53Z"
                 + "<br/><b>Screen Size</b>: 3.0 Inches<br/><b>Brand</b>: Minolta"
                 + "<br/><b>Optical Zoom</b>: 53 x</html>";

               CameraFrame.pdetails=str;
               CameraFrame.pname = "camera4";
               CameraFrame.jButton1.setVisible(false);
               CameraFrame.jButton3.setVisible(true);
           
            value=4;
               
                      
           }
         GestureInfo.ht.setCameraDetailInfoFrameObject(null);
            this.dispose();
            CameraFrame pf = new CameraFrame();
            pf.count=value;
             GestureInfo.ht.setCameraFrameObject(pf);
            pf.setVisible(true);
            pf.setExtendedState(MAXIMIZED_BOTH);
            pf.getContentPane().setBackground(Color.WHITE);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraDetailInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraDetailInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraDetailInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraDetailInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraDetailInfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
