/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gesturebasedshopping;

import java.awt.AWTException;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JLabel;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
     int buttonno=0,x=0;
    public MainFrame() {
        initComponents();
      GestureInfo.frameno=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("MARINE ELECTRONICS ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 990, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 110, 1270, 340);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Show these Gestures");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 530, 170, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Enter.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(790, 567, 96, 133);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Previous.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 568, 96, 132);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next.jpeg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 570, 96, 130);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton1.setText("Buy Television");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(80, 470, 250, 50);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton2.setText("Buy Phones");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(410, 470, 230, 50);

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton3.setText("Buy Cameras");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(720, 470, 270, 50);

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButton4.setText("Buy Washing Machine");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(1040, 470, 280, 50);

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1230, 40, 110, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        openTelevisionFrame();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
         openMobileFrame();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
         openCameraFrame();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        openWMachineFrame();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed
     
     public void toggle()
    {
        System.out.println("In toggle function()");
      x=buttonno%4;
        System.out.println("X = "+x);
      if(x==0)
      {
          System.out.println("Button one selected");
          jToggleButton1.setSelected(true);
          jToggleButton2.setSelected(false);
           jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
          
      }
        
      else if(x==1)
       {
             System.out.println("Button Two selected");
           jToggleButton1.setSelected(false);
          jToggleButton2.setSelected(true);
           jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(false);
          
           
       }
        
       
       else if(x==2)
        {
              System.out.println("Button Three selected");
          jToggleButton1.setSelected(false);
          jToggleButton2.setSelected(false);
           jToggleButton3.setSelected(true);
            jToggleButton4.setSelected(false);
           
        }
        
        
        else if(x==3)
         {
               System.out.println("Button Four selected");
            jToggleButton1.setSelected(false);
          jToggleButton2.setSelected(false);
           jToggleButton3.setSelected(false);
            jToggleButton4.setSelected(true);
           
           
         }
        
        
       buttonno=buttonno+1;  
    }
    
    public void press() throws AWTException
    {
      if(x==0)
      {
        openTelevisionFrame();
          
      }
        
       if(x==1)
       {
           openMobileFrame();
           
       }
        
       
        if(x==2)
        {
              openCameraFrame();
           
        }
        
        
         if(x==3)
         {
               openWMachineFrame();
           
         }
    }
    
  public  void openTelevisionFrame(){
         GestureInfo.ht.setMainFrameObject(null);
        this.dispose();
        TelevisionFrame lf = new TelevisionFrame();
        lf.count=1;
                GestureInfo.ht.setTelevisionFrameObject(lf);

        lf.getContentPane().setBackground(Color.WHITE);
        lf.setVisible(true);
        lf.setExtendedState(MAXIMIZED_BOTH);
    }
   public void openMobileFrame(){
        GestureInfo.ht.setMainFrameObject(null);
        this.dispose();
        MobileFrame lf = new MobileFrame();
        lf.count=1;
         GestureInfo.ht.setMobileFrameObject(lf);
        lf.getContentPane().setBackground(Color.WHITE);
        lf.setVisible(true);
        lf.setExtendedState(MAXIMIZED_BOTH);
       
    }
  public  void openCameraFrame(){
        GestureInfo.ht.setMainFrameObject(null);
        this.dispose();
        CameraFrame lf = new CameraFrame();
        lf.count=1;
          GestureInfo.ht.setCameraFrameObject(lf);
        lf.getContentPane().setBackground(Color.WHITE);
        lf.setVisible(true);
        lf.setExtendedState(MAXIMIZED_BOTH);
      
    }
   public void openWMachineFrame(){
        GestureInfo.ht.setMainFrameObject(null);
        this.dispose();
        WashingMachineFrame lf = new WashingMachineFrame();
        lf.count=1;
        GestureInfo.ht.setWashingMachineFrameObject(lf);
        lf.getContentPane().setBackground(Color.WHITE);
        lf.setVisible(true);
        lf.setExtendedState(MAXIMIZED_BOTH);
       
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
