/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gesturebasedshopping;


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class MobileFrame extends javax.swing.JFrame {
    public   int count=1;
    public static String pname="mobile1";
    public static String pdname="<html><c>Moto G Stylus | 2022</c></html>";
    public static String path="/mobile1.jpg";
    public static String pdetails="<html><b>Price</b>: $179.00<br/><b>Model Number</b>: Moto G Stylus"
                 + "<br/><b>Screen Size</b>: 6.8 Inches<br/><b>Brand</b>: MOTOROLA"
                 + "<br/><b>OS</b>: Android 10.0</html>";
   
    /**
     * Creates new form StoreFrame
     */
    public MobileFrame() {
        initComponents();
         jLabel3.setHorizontalAlignment(JLabel.CENTER);
         jLabel3.setSize(300, 400);
         jButton2.setOpaque(false);       
         jLabel4.setText(pdname);
         jLabel3.setIcon(resizeIcon(path));
         jLabel5.setText(pdetails);
                 
         if(pname.equals("mobile1"))
             jButton3.setVisible(false);
         if(pname.equals("mobile4"))
             jButton1.setVisible(false);
                    
         GestureInfo.frameno=3;
    }
     ImageIcon resizeIcon(String path)
    {
        ImageIcon icon=new ImageIcon (getClass().getResource(path));
        Image image = icon.getImage().getScaledInstance(416, 250, Image.SCALE_DEFAULT); // transform it 
        icon = new ImageIcon(image);
        return icon;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rightarrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("More Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leftarrow.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 130, 910, 580);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("MARINE ELECTRONICS ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 990, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1120, 530, 96, 129);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Previous.jpeg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(990, 380, 96, 129);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next.jpeg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1120, 380, 96, 129);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moreinfo.jpeg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1000, 530, 96, 129);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Show these Gestures");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1020, 330, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainFrame();
    }//GEN-LAST:event_jButton4ActionPerformed
    public void mainFrame(){
        GestureInfo.ht.setMobileFrameObject(null);
       this.dispose();
         MainFrame lf = new MainFrame();
          GestureInfo.ht.setMainFrameObject(lf);
         lf.getContentPane().setBackground(Color.WHITE);
         lf.setVisible(true);
         lf.setExtendedState(MAXIMIZED_BOTH);
        
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        funPrevious();

    }//GEN-LAST:event_jButton3ActionPerformed

     public void funPrevious()
    {
        System.out.println("Count "+count);
         if(count==4)
        {
         jLabel4.setText("<html><c>OnePlus Nord N20 5G</c></html>");
         jLabel3.setIcon(resizeIcon("/mobile3.jpg"));
         String str="<html><b>Price</b>: $249.00<br/><b>Model Number</b>: Nord N20"
                 + "<br/><b>Screen Size</b>: 6.43 Inches<br/><b>Brand</b>: OnePlus"
                 + "<br/><b>OS</b>: OxygenOS</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
         count--;
         
           
        }
        else if(count==3)
        {
         jLabel4.setText("<html><c>SAMSUNG Galaxy A03 Core</c></html>");
         jLabel3.setIcon(resizeIcon("/mobile2.jpg"));
         String str="<html><b>Price</b>: $85.00<br/><b>Model Number</b>: Galaxy A03 Core"
                 + "<br/><b>Screen Size</b>: 6.8 Inches<br/><b>Brand</b>: SAMSUNG"
                 + "<br/><b>OS</b>: Android 11.0</html>";
         
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
          count--;
         
           
        }
        else if(count==2)
        {
         jLabel4.setText("<html><c>Moto G Stylus | 2022</c></html>");
         jLabel3.setIcon(resizeIcon("/mobile1.jpg"));
         String str="<html><b>Price</b>: $179.00<br/><b>Model Number</b>: Moto G Stylus"
                 + "<br/><b>Screen Size</b>: 6.8 Inches<br/><b>Brand</b>: MOTOROLA"
                 + "<br/><b>OS</b>: Android 10.0</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(false);
         count--;  
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        productDetails();

    }//GEN-LAST:event_jButton2ActionPerformed

   public  void productDetails()
    { 
          if(count==1)
          {
           
            MobileDetailInfoFrame.path1="/mobile1.jpg";
            MobileDetailInfoFrame.path2="/mobile1_1.jpg";
            MobileDetailInfoFrame.path3="/mobile1_2.jpg";
            MobileDetailInfoFrame.path4="/mobile1_3.jpg";
            MobileDetailInfoFrame.path5="/mobile1_4.jpg";
            MobileDetailInfoFrame.pdname="<html><c>Moto G Stylus | 2022</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Wireless Carrier: Unlocked"
                    + "<br/>Cellular Technology: 4G, 3G"
                 + "<br/>Memory Storage Capacity: 128 GB"
                    + "<br/>Connectivity Technologies: Bluetooth, Wi-Fi, USB"
                 + "<br/>Wireless Network Technology : GSM, CDMA, LTE</html>";
            MobileDetailInfoFrame.pdetails=details;
            MobileDetailInfoFrame.pname="mobile1";
            
            
          
          }
          else if(count==2)
          {
            pname=pname.trim();
            MobileDetailInfoFrame.path1="/mobile2.jpg";
            MobileDetailInfoFrame.path2="/mobile2_1.jpg";
            MobileDetailInfoFrame.path3="/mobile2_2.jpg";
            MobileDetailInfoFrame.path4="/mobile2_3.jpg";
            MobileDetailInfoFrame.path5="/mobile2_4.jpg";
            MobileDetailInfoFrame.pdname="<html><c>SAMSUNG Galaxy A03 Core</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Wireless Carrier: Unlocked for All Carriers"
                    + "<br/>Cellular Technology: LTE, GSM,UMTS"
                 + "<br/>Memory Storage Capacity: 32 GB"
                    + "<br/>Connectivity Technologies: Bluetooth, Wi-Fi, USB"
                 + "<br/>Wireless Network Technology : GSM, LTE</html>";
            MobileDetailInfoFrame.pdetails=details;
            MobileDetailInfoFrame.pname="mobile2";
          
          }
           else if(count==3)
          {
            pname=pname.trim();
            MobileDetailInfoFrame.path1="/mobile3.jpg";
            MobileDetailInfoFrame.path2="/mobile3_1.jpg";
            MobileDetailInfoFrame.path3="/mobile3_2.jpg";
            MobileDetailInfoFrame.path4="/mobile3_3.jpg";
            MobileDetailInfoFrame.path5="/mobile3_4.jpg";
            MobileDetailInfoFrame.pdname="<html><c>OnePlus Nord N20 5G</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Wireless Carrier: Unlocked"
                    + "<br/>Cellular Technology: 5G"
                 + "<br/>Memory Storage Capacity: 128 GB"
                    + "<br/>Connectivity Technologies: Bluetooth, Wi-Fi, USB"
                 + "<br/>Wireless Network Technology : Wi-Fi</html>";
            MobileDetailInfoFrame.pdetails=details;
            MobileDetailInfoFrame.pname="mobile3";
          
          }
          else if(count==4)
          {
            pname=pname.trim();
            MobileDetailInfoFrame.path1="/mobile4.jpg";
            MobileDetailInfoFrame.path2="/mobile4_1.jpg";
            MobileDetailInfoFrame.path3="/mobile4_2.jpg";
            MobileDetailInfoFrame.path4="/mobile4_3.jpg";
            MobileDetailInfoFrame.path5="/mobile4_4.jpg";
            MobileDetailInfoFrame.pdname="<html><c>BLU F92e 5G | 2023</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Wireless Carrier: Unlocked for All Carriers"
                    + "<br/>Cellular Technology: 5G"
                 + "<br/>Memory Storage Capacity: 128 GB"
                    + "<br/>Connectivity Technologies: Wi-Fi"
                 + "<br/>Wireless Network Technology : GSM, LTE</html>";
            MobileDetailInfoFrame.pdetails=details;
            MobileDetailInfoFrame.pname="mobile4";
          
          }
            GestureInfo.ht.setMobileFrameObject(null);
            this.dispose();
            MobileDetailInfoFrame tf = new MobileDetailInfoFrame();
            GestureInfo.ht.setMobileDetailInfoFrameObject(tf);
            tf.setVisible(true);
            tf.setExtendedState(MAXIMIZED_BOTH);
            tf.getContentPane().setBackground(Color.WHITE);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        funNext();

    }//GEN-LAST:event_jButton1ActionPerformed
  public void funNext()
    {
        if(count==1)
        {
                    
         jLabel4.setText("<html><c>SAMSUNG Galaxy A03 Core</c></html>");
         jLabel3.setIcon(resizeIcon("/mobile2.jpg"));
         String str="<html><b>Price</b>: $85.00<br/><b>Model Number</b>: Galaxy A03 Core"
                 + "<br/><b>Screen Size</b>: 6.8 Inches<br/><b>Brand</b>: SAMSUNG"
                 + "<br/><b>OS</b>: Android 11.0</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
               
        }   
        
         else if(count==2)
        {
                    
         jLabel4.setText("<html><c>OnePlus Nord N20 5G</c></html>");
         jLabel3.setIcon(resizeIcon("/mobile3.jpg"));
         String str="<html><b>Price</b>: $249.00<br/><b>Model Number</b>: Nord N20"
                 + "<br/><b>Screen Size</b>: 6.43 Inches<br/><b>Brand</b>: OnePlus"
                 + "<br/><b>OS</b>: OxygenOS</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
                 
        } 
        else if(count==3)
        {
                    
         jLabel4.setText("<html><c>BLU F92e 5G | 2023</c></html>");
         jLabel3.setIcon(resizeIcon("/mobile4.jpg"));
         String str="<html><b>Price</b>: $149.99<br/><b>Model Number</b>: F92e 5G"
                 + "<br/><b>Screen Size</b>: 6.5 Inches<br/><b>Brand</b>: BLU"
                 + "<br/><b>OS</b>: Android 12.0</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
         jButton1.setVisible(false);
                  
        } 
    }
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MobileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MobileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MobileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MobileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MobileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
