/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gesturebasedshopping;


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class WashingMachineFrame extends javax.swing.JFrame {
    public  int count=1;
    public static String pname="wmachine1";
    public static String pdname="<html><c>Giantex Full-Automatic Washing</c></html>";
    public static String path="/wmachine1.jpg";
    public static String pdetails="<html><b>Price</b>: $249.99<br/><b>Model Number</b>: ‎EP23113"
                 + "<br/><b>Item Weight</b>: 0.01 ounces<br/><b>Brand</b>: Giantex"
                 + "<br/><b>Material</b>: Polypropylene, Stainless Steel, Aluminium</html>";
   
    /**
     * Creates new form StoreFrame
     */
    public WashingMachineFrame() {
        initComponents();
         jLabel3.setHorizontalAlignment(JLabel.CENTER);
         jLabel3.setSize(300, 400);
         jButton2.setOpaque(false);       
         jLabel4.setText(pdname);
         jLabel3.setIcon(resizeIcon(path));
         jLabel5.setText(pdetails);
                 
         if(pname.equals("wmachine1"))
             jButton3.setVisible(false);
         if(pname.equals("wmachine4"))
             jButton1.setVisible(false);
                
         GestureInfo.frameno=5;
    }
     ImageIcon resizeIcon(String path)
    {
        ImageIcon icon=new ImageIcon (getClass().getResource(path));
        Image image = icon.getImage().getScaledInstance(416, 250, Image.SCALE_DEFAULT); // transform it 
        icon = new ImageIcon(image);
        return icon;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rightarrow.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("More Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/leftarrow.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("MARINE ELECTRONICS ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Show these Gestures");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Previous.jpeg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Next.jpeg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Moreinfo.jpeg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(528, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(855, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mainFrame();
    }//GEN-LAST:event_jButton4ActionPerformed

    public  void mainFrame(){
          GestureInfo.ht.setWashingMachineFrameObject(null);
          this.dispose();
         MainFrame lf = new MainFrame();
         GestureInfo.ht.setMainFrameObject(lf);
         lf.getContentPane().setBackground(Color.WHITE);
         lf.setVisible(true);
         lf.setExtendedState(MAXIMIZED_BOTH);
         
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        funPrevious();

    }//GEN-LAST:event_jButton3ActionPerformed

     public void funPrevious()
    {
        System.out.println("Count "+count);
         if(count==4)
        {
          jLabel4.setText("<html><c>Giantex Portable Washing Machine</c></html>");
         jLabel3.setIcon(resizeIcon("/wmachine3.jpg"));
         String str="<html><b>Price</b>: $199.99<br/><b>Model Number</b>: ‎GT10093US-BL-PF"
                 + "<br/><b>Item Weight</b>: ‎17.6 pounds<br/><b>Brand</b>: Giantex"
                 + "<br/><b>Access Location</b>: Top Load</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
         count--;
         
           
        }
        else if(count==3)
        {
          jLabel4.setText("<html><c>Pyle Compact Home Washer</c></html>");
         jLabel3.setIcon(resizeIcon("/wmachine2.jpg"));
         String str="<html><b>Price</b>: $179.99<br/><b>Model Number</b>: PUCWM23"
                 + "<br/><b>Item Weight</b>: 7.7 pounds<br/><b>Brand</b>: Pyle"
                 + "<br/><b>Installation Type</b>: ‎Free Standing</html>";
         
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(true);
          count--;
         
           
        }
        else if(count==2)
        {
         jLabel4.setText("<html><c>Giantex Full-Automatic Washing</c></html>");
         jLabel3.setIcon(resizeIcon("/wmachine1.jpg"));
         String str="<html><b>Price</b>: $249.99<br/><b>Model Number</b>: ‎EP23113"
                 + "<br/><b>Item Weight</b>: 0.01 ounces<br/><b>Brand</b>: Giantex"
                 + "<br/><b>Material</b>: Polypropylene, Stainless Steel, Aluminium</html>";
         jLabel5.setText(str);
         jButton1.setVisible(true);
         jButton3.setVisible(false);
         count--;  
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        productDetails();

    }//GEN-LAST:event_jButton2ActionPerformed

     public void productDetails()
    { 
          if(count==1)
          {
           
            WmachineDetailInfoFrame.path1="/wmachine1.jpg";
            WmachineDetailInfoFrame.path2="/wmachine1_1.jpg";
            WmachineDetailInfoFrame.path3="/wmachine1_2.jpg";
            WmachineDetailInfoFrame.path4="/wmachine1_3.jpg";
            WmachineDetailInfoFrame.path5="/wmachine1_4.jpg";
            WmachineDetailInfoFrame.pdname="<html><c>Giantex Full-Automatic Washing</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Product Dimensions: 19.7\"D x 19.8\"W x 33.6\"H"
                    + "<br/>Special Feature: Full-automatic"
                 + "<br/>Capacity: 9.92 Pounds"
                    + "<br/>Human Interface Input: Buttons"
                 + "<br/>Color: Gray</html>";
            WmachineDetailInfoFrame.pdetails=details;
            WmachineDetailInfoFrame.pname="wmachine1";
            
            
          
          }
          else if(count==2)
          {
            pname=pname.trim();
            WmachineDetailInfoFrame.path1="/wmachine2.jpg";
            WmachineDetailInfoFrame.path2="/wmachine2_1.jpg";
            WmachineDetailInfoFrame.path3="/wmachine2_2.jpg";
            WmachineDetailInfoFrame.path4="/wmachine2_3.jpg";
            WmachineDetailInfoFrame.path5="/wmachine2_4.jpg";
            WmachineDetailInfoFrame.pdname="<html><c>Pyle Compact Home Washer</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Product Dimensions: 13.9\"D x 22.2\"W x 23.6\"H"
                    + "<br/>Special Feature: Compact & Portable, Energy & Water Efficient"
                 + "<br/>Capacity: 7.7 Pounds"
                    + "<br/>Human Interface Input: Knob"
                 + "<br/>Color: Dark Gray</html>";
            WmachineDetailInfoFrame.pdetails=details;
            WmachineDetailInfoFrame.pname="wmachine2";
          
          }
           else if(count==3)
          {
            pname=pname.trim();
             WmachineDetailInfoFrame.path1="/wmachine3.jpg";
            WmachineDetailInfoFrame.path2="/wmachine3_1.jpg";
            WmachineDetailInfoFrame.path3="/wmachine3_2.jpg";
            WmachineDetailInfoFrame.path4="/wmachine3_3.jpg";
            WmachineDetailInfoFrame.path5="/wmachine3_4.jpg";
            WmachineDetailInfoFrame.pdname="<html><c>Giantex Portable Washing Machine</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Product Dimensions: 16\"D x 27.5\"W x 32\"H"
                    + "<br/>Special Feature: Portable,Dual Motor,Semi-automatic"
                 + "<br/>Capacity: 17.6 Pounds"
                    + "<br/>Human Interface Input: Washer and Spinner Combo"
                 + "<br/>Color: Blue,White</html>";
            WmachineDetailInfoFrame.pdetails=details;
            WmachineDetailInfoFrame.pname="wmachine3";
          
          }
          else if(count==4)
          {
            pname=pname.trim();
             WmachineDetailInfoFrame.path1="/wmachine4.jpg";
            WmachineDetailInfoFrame.path2="/wmachine4_1.jpg";
            WmachineDetailInfoFrame.path3="/wmachine4_2.jpg";
            WmachineDetailInfoFrame.path4="/wmachine4_3.jpg";
            WmachineDetailInfoFrame.path5="/wmachine4_4.jpg";
            WmachineDetailInfoFrame.pdname="<html><c>EZ Laundry 29\" Universal Fit Laundry</c></html>";
            String details="<html><b>About this item</b>"
                    + "<br/>Product Dimensions: 29\"L x 29\"W x 14.3\"H"
                    + "<br/>Special Feature: Universal fit, drainage feature, custom fit hamper"
                 + "<br/>Capacity: ‎400 Pounds"
                    + "<br/>Material: Alloy Steel"
                 + "<br/>Color: White</html>";
            WmachineDetailInfoFrame.pdetails=details;
            WmachineDetailInfoFrame.pname="wmachine4";
          
          }
           GestureInfo.ht.setWashingMachineFrameObject(null);
            this.dispose();
            WmachineDetailInfoFrame tf = new WmachineDetailInfoFrame();
             GestureInfo.ht.setWmachineDetailInfoFrameObject(tf);
            tf.setVisible(true);
            tf.setExtendedState(MAXIMIZED_BOTH);
            tf.getContentPane().setBackground(Color.WHITE);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        funNext();

    }//GEN-LAST:event_jButton1ActionPerformed
  void funNext()
    {
        if(count==1)
        {
                    
         jLabel4.setText("<html><c>Pyle Compact Home Washer</c></html>");
         jLabel3.setIcon(resizeIcon("/wmachine2.jpg"));
         String str="<html><b>Price</b>: $179.99<br/><b>Model Number</b>: PUCWM23"
                 + "<br/><b>Item Weight</b>: 7.7 pounds<br/><b>Brand</b>: Pyle"
                 + "<br/><b>Installation Type</b>: ‎Free Standing</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
               
        }   
        
         else if(count==2)
        {
                    
         jLabel4.setText("<html><c>Giantex Portable Washing Machine</c></html>");
         jLabel3.setIcon(resizeIcon("/wmachine3.jpg"));
         String str="<html><b>Price</b>: $199.99<br/><b>Model Number</b>: ‎GT10093US-BL-PF"
                 + "<br/><b>Item Weight</b>: ‎17.6 pounds<br/><b>Brand</b>: Giantex"
                 + "<br/><b>Access Location</b>: Top Load</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
                 
        } 
        else if(count==3)
        {
                    
         jLabel4.setText("<html><c>EZ Laundry 29\" Universal Fit Laundry</c></html>");
         jLabel3.setIcon(resizeIcon("/wmachine4.jpg"));
         String str="<html><b>Price</b>: $169.99<br/><b>Model Number</b>: EZ Laundry"
                 + "<br/><b>Item Weight</b>: 33.2 pounds<br/><b>Brand</b>: EZ Laundry"
                 + "<br/><b>Size</b>: ‎29''</html>";
         
         count++;
         jLabel5.setText(str);
         jButton3.setVisible(true);
         jButton1.setVisible(false);
                  
        } 
    }
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WashingMachineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WashingMachineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WashingMachineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WashingMachineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WashingMachineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
